# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
formatter:
  trailing_commas: preserve

# 그 외
linter:
  rules:
    prefer_const_constructors: true # constructor가 위에 위치
    prefer_const_literals_to_create_immutables: true # 가능하면 const를 쓰라는 경고
    avoid_print: false # print 사용 시 경고 안함
    prefer_final_fields: true # 불변 필드는 final 
    always_use_package_imports: true # 상대경로 대신 package import 쓰기
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true # 위젯 생성자에 Key 넣으라는 규칙